# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=30, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product.', max_digits=7, verbose_name='Price')),
                ('stock_quantity', models.IntegerField(help_text='The quantity of this product that you have in stock.', verbose_name='Stock Quantity')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='products/')),
            ],
        ),
    ]
