# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(help_text='Choose an image for the product.', upload_to='products/'),
        ),
    ]
