# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180402_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the product.', max_length=60, verbose_name='Name'),
        ),
    ]
