# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 19:21
from __future__ import unicode_literals

import backend.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180402_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(help_text='Choose an image for the product.', upload_to=backend.models.get_photo_path),
        ),
    ]
